import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { renderReport, reportFilename, writeReport } from "../../src/incidents/report.js";
import type { Incident } from "../../src/incidents/types.js";

const incident: Incident = {
  id: "i1",
  detectedAt: "2026-06-23T14:33:01.000Z",
  severity: "critical",
  title: "Build failed · main · dep bump",
  rootCause: "axios 1.6.2 → 1.7.0 broke interceptors",
  suggestedAction: "pin axios to 1.6.2",
  patternMatch: "similar on 2024-11-14",
  confidence: "medium",
  timeline: [{ time: "14:29:01", text: "push to main", source: "git" }],
  eventIds: ["e1"],
  brainLabel: "claude-sonnet-4-6 via claude-cli",
};

describe("reportFilename", () => {
  it("is colon-free and Windows-safe", () => {
    const name = reportFilename("2026-06-23T14:33:01.000Z");
    expect(name).not.toContain(":");
    expect(name).toMatch(/^\d{4}-\d{2}-\d{2}-\d{6}\.md$/);
  });
});

describe("renderReport", () => {
  it("renders the ☠ title and all sections", () => {
    const md = renderReport(incident);
    expect(md).toContain("# ☠ Incident Report");
    expect(md).toContain("**Severity:** CRITICAL");
    expect(md).toContain("## Likely Cause");
    expect(md).toContain("axios 1.6.2");
    expect(md).toContain("## Suggested Action");
    expect(md).toContain("## Timeline");
    expect(md).toContain("push to main");
    expect(md).toContain("Generated by postmortem ☠");
  });
});

describe("writeReport", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "mort-report-"));
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it("writes the report and returns a colon-free path", () => {
    const path = writeReport(dir, incident);
    expect(path).not.toContain(".md:");
    const contents = readFileSync(path, "utf8");
    expect(contents).toContain("Build failed · main");
  });
});
